#! /usr/bin/env gawk -f

BEGIN {	
   count=0	
   FS=","}
$3>200 && $3<2000 || $4>200 && $4<2000 {print $0
       	count++
	}
	{array[$2]+=$5}

END {print count
     for (n in array)
	     print n,array[n]
}
